"""Export and import the demo corpus without spending a single model call.

The problem this solves: extracting the committed corpus cost real Gemini
calls, over real time, against a quota that used to be a single point of
failure. Nobody who clones this repo -- a grader, a reviewer, this project's
own CI -- should have to pay that cost again just to see a populated knowledge
layer, and a deployed instance whose database is ever lost (an accidental
reset, a fresh volume) shouldn't either.

What this ships and what it doesn't. `export` dumps DATA ONLY -- documents,
chunks, facts, fact_attributes, fact_types, embeddings, and relationships --
as plain INSERT statements, with every id preserved exactly. That last part is
not cosmetic: docs/DEMO_CASES.md cites specific fact and relationship ids
(fact 238, relationship 14, ...), and a seed that renumbered them on import
would silently break every citation in that document. It does NOT ship the
source PDFs. Those were gitignored from the start (see backend/.gitignore),
and this script does not change that policy -- it is a database snapshot, not
a document archive. A fact's stored quote and grounding metadata still work
fully without the PDF; only the page-image highlight in the evidence viewer
needs the underlying file, and GET /facts/{id}/evidence already degrades to
`grounded: false` rather than erroring when it's absent -- see that endpoint's
docstring in api/facts.py.

Usage:
    python scripts/seed_demo.py export [--out seed/demo_corpus.sql]
    python scripts/seed_demo.py import [--force]

`import` refuses to touch a database that already has facts in it, unless
--force is passed -- a seed script's job is to populate emptiness, not to
silently overwrite someone's real corpus.
"""

from __future__ import annotations

import argparse
import re
import sqlite3
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[1]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from app.core.config import settings  # noqa: E402
from app.db.database import get_conn, init_db  # noqa: E402

DEFAULT_SEED_PATH = BACKEND_DIR / "seed" / "demo_corpus.sql"

# Data tables only, in FK-dependency order -- matches schema.sql's own
# CREATE TABLE order, which is why a plain iterdump() filtered to just these
# names is already safe to replay without a foreign-key error.
TABLES = (
    "documents",
    "chunks",
    "facts",
    "fact_attributes",
    "fact_types",
    "embeddings",
    "relationships",
    "review_queue",
)

_INSERT_TABLE = re.compile(r'^INSERT INTO ["\']?(\w+)["\']?')
_SEQUENCE_NAME = re.compile(r"^INSERT INTO sqlite_sequence VALUES\('(\w+)'")


def export_seed(source_db: Path, out_path: Path) -> dict[str, int]:
    """Write a data-only SQL dump of `TABLES` from `source_db` to `out_path`.

    Built on sqlite3's own iterdump() rather than a hand-rolled INSERT
    builder specifically for its BLOB handling: `embeddings.vector` is a raw
    float32 buffer, and iterdump() already emits the correct `X'...'` hex
    literal for it. Reimplementing that is exactly the kind of detail that
    silently corrupts a vector on the first attempt.
    """
    conn = sqlite3.connect(f"file:{source_db}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    try:
        counts = {
            table: conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
            for table in TABLES
        }
        # iterdump() emits tables in ALPHABETICAL order, not creation order --
        # "embeddings" comes out before "facts", "chunks" before "documents".
        # Foreign keys are enforced on import, so inserting a child before its
        # parent fails immediately. Bucketing by table and replaying in
        # TABLES order (which matches schema.sql's FK-dependency order) fixes
        # that; sqlite_sequence rows go last since they reference no FK.
        inserts: dict[str, list[str]] = {table: [] for table in TABLES}
        sequences: list[str] = []
        for statement in conn.iterdump():
            table_match = _INSERT_TABLE.match(statement)
            if table_match and table_match.group(1) in TABLES:
                inserts[table_match.group(1)].append(statement)
                continue
            seq_match = _SEQUENCE_NAME.match(statement)
            if seq_match and seq_match.group(1) in TABLES:
                sequences.append(statement)

        lines = [
            "-- Generated by scripts/seed_demo.py export. Do not hand-edit --",
            "-- run the export again after re-ingesting instead.",
            "BEGIN TRANSACTION;",
        ]
        for table in TABLES:
            lines.extend(inserts[table])
        lines.extend(sequences)
        lines.append("COMMIT;")
    finally:
        conn.close()

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return counts


def import_seed(conn: sqlite3.Connection, sql_path: Path, *, force: bool = False) -> dict[str, int]:
    """Load a seed produced by `export_seed` into an already-migrated database.

    Refuses a non-empty database unless `force`, and `force` clears exactly
    the tables this script owns -- explicit DELETEs rather than relying on
    cascades, because fact_types has no FK to facts (a fact's type surviving
    its own deletion is correct there) and would otherwise be left stale.
    """
    existing_facts = conn.execute("SELECT COUNT(*) FROM facts").fetchone()[0]
    if existing_facts and not force:
        raise RuntimeError(
            f"database already has {existing_facts} fact(s); pass --force to "
            f"replace them, or point at an empty database"
        )

    if not sql_path.exists():
        raise FileNotFoundError(f"no seed file at {sql_path}")

    if existing_facts:
        for table in reversed(TABLES):
            conn.execute(f"DELETE FROM {table}")
        conn.execute(
            "DELETE FROM sqlite_sequence WHERE name IN ({})".format(
                ",".join("?" for _ in TABLES)
            ),
            TABLES,
        )

    conn.executescript(sql_path.read_text(encoding="utf-8"))
    conn.commit()

    return {
        table: conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
        for table in TABLES
    }


def _main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    export_p = sub.add_parser("export", help="Dump the current database to a seed file")
    export_p.add_argument("--source", type=Path, default=settings.database_file)
    export_p.add_argument("--out", type=Path, default=DEFAULT_SEED_PATH)

    import_p = sub.add_parser("import", help="Load a seed file into the configured database")
    import_p.add_argument("--seed", type=Path, default=DEFAULT_SEED_PATH)
    import_p.add_argument(
        "--force", action="store_true", help="Replace an existing non-empty corpus"
    )

    args = parser.parse_args()

    if args.command == "export":
        counts = export_seed(args.source, args.out)
        print(f"wrote {args.out} from {args.source}")
        for table, n in counts.items():
            print(f"  {table:<18} {n}")
        return

    init_db(settings.database_file)
    with get_conn(settings.database_file) as conn:
        try:
            counts = import_seed(conn, args.seed, force=args.force)
        except RuntimeError as exc:
            print(f"error: {exc}", file=sys.stderr)
            sys.exit(1)
    print(f"seeded {settings.database_file} from {args.seed}")
    for table, n in counts.items():
        print(f"  {table:<18} {n}")


if __name__ == "__main__":
    _main()
